// 口播工程 public/ 素材清单（由目录扫描生成）
export type MediaItem = { file: string; label: string; kind: "video" | "image" | "audio" };
export const MEDIA_ITEMS: MediaItem[] = [
  { file: "dh/host.webm", label: "数字人 host", kind: "video" },
  { file: "full.wav", label: "配音 full.wav", kind: "audio" },
  { file: "broll/creator-2948.mp4", label: "broll creator-2948.mp4", kind: "video" },
  { file: "broll/creator-41290.mp4", label: "broll creator-41290.mp4", kind: "video" },
  { file: "broll/creator-42323.mp4", label: "broll creator-42323.mp4", kind: "video" },
  { file: "shots/clip-h.mp4", label: "shots clip-h.mp4", kind: "video" },
  { file: "shots/clip-m.mp4", label: "shots clip-m.mp4", kind: "video" },
  { file: "shots/clip-v.mp4", label: "shots clip-v.mp4", kind: "video" },
  { file: "shots/demo.png", label: "shots demo.png", kind: "image" },
  { file: "shots/gallery-full.png", label: "shots gallery-full.png", kind: "image" },
  { file: "shots/gallery.png", label: "shots gallery.png", kind: "image" },
  { file: "shots/github.png", label: "shots github.png", kind: "image" },
  { file: "shots/hand-pencil.png", label: "shots hand-pencil.png", kind: "image" },
  { file: "shots/skill-page.png", label: "shots skill-page.png", kind: "image" },
];

export const SFX_ALL: string[] = [
  "click.mp3",
  "ding.mp3",
  "paper.mp3",
  "pk-camera-camera-lens-shutter.mp3",
  "pk-camera-click-camera.mp3",
  "pk-camera-ui-zoom-in.mp3",
  "pk-counter-clock-tick-single.mp3",
  "pk-data-data-load-os.mp3",
  "pk-impact-hit-fast-exciting.mp3",
  "pk-impact-impact-deep-whoosh.mp3",
  "pk-mech-lock-quick.mp3",
  "pk-paper-paper-slice-quick.mp3",
  "pk-paper-paper-slide.mp3",
  "pk-scifi-hitech-bleep.mp3",
  "pk-scifi-scifi-click.mp3",
  "pk-text-keyboard.mp3",
  "pk-text-marker-pen-line.mp3",
  "pk-text-pencil-write-short.mp3",
  "pk-text-typewriter-hit-soft.mp3",
  "pk-transition-air-whoosh-powerful.mp3",
  "pk-transition-sweep-scifi-fast.mp3",
  "pk-transition-transition-soft.mp3",
  "pk-transition-wind-swoosh-short.mp3",
  "pk-ui-pop.mp3",
  "pk-ui-ui-click-tone.mp3",
  "pop.mp3",
  "scratch.mp3",
  "slam.mp3",
  "swipe.mp3",
  "tick.mp3",
  "typekey-1.mp3",
  "typekey-2.mp3",
  "whoosh.mp3",
];
