// 自动生成，勿手改：node scripts/gen-index.mjs
import type React from "react";
import * as t0 from "@tpl/alt-block-lines";
import * as t1 from "@tpl/bar-chart-growth";
import * as t2 from "@tpl/bed-echo-blur";
import * as t3 from "@tpl/behind-text-title";
import * as t4 from "@tpl/black-slam-transition";
import * as t5 from "@tpl/callout-line-label";
import * as t6 from "@tpl/caret-wipe-transition";
import * as t7 from "@tpl/chapter-progress-list";
import * as t8 from "@tpl/chapter-title-card";
import * as t9 from "@tpl/chart-grow";
import * as t10 from "@tpl/chat-gpt";
import * as t11 from "@tpl/chat-message-flow";
import * as t12 from "@tpl/chevron-lower-third";
import * as t13 from "@tpl/claude-code";
import * as t14 from "@tpl/color-slam-beat-card";
import * as t15 from "@tpl/converging-arrows";
import * as t16 from "@tpl/corner-bracket-frame";
import * as t17 from "@tpl/count-badge-title";
import * as t18 from "@tpl/cursor-actor-demo";
import * as t19 from "@tpl/cursor-locked-zoom";
import * as t20 from "@tpl/danmu-bubble-praise";
import * as t21 from "@tpl/douyin-follow-card";
import * as t22 from "@tpl/evidence-scroll-tour";
import * as t23 from "@tpl/filmstrip-conveyor";
import * as t24 from "@tpl/focus-dim-spotlight";
import * as t25 from "@tpl/glass-code-walk";
import * as t26 from "@tpl/gooey-morph";
import * as t27 from "@tpl/grid-to-hero";
import * as t28 from "@tpl/hand-drawn-ellipse";
import * as t29 from "@tpl/highlighter-sweep";
import * as t30 from "@tpl/host-shrink-to-chip";
import * as t31 from "@tpl/impact-open-title";
import * as t32 from "@tpl/info-term-card";
import * as t33 from "@tpl/ink-underline";
import * as t34 from "@tpl/keyword-pop-highlight";
import * as t35 from "@tpl/line-by-line-slide";
import * as t36 from "@tpl/line-chart-story-draw";
import * as t37 from "@tpl/logo-enter";
import * as t38 from "@tpl/long-take-world";
import * as t39 from "@tpl/lower-third-nameplate";
import * as t40 from "@tpl/magnifier-detail";
import * as t41 from "@tpl/map-route-pin";
import * as t42 from "@tpl/media-pop-in";
import * as t43 from "@tpl/metric-with-sparkline";
import * as t44 from "@tpl/motion-blur-slam-in";
import * as t45 from "@tpl/multi-still-tour";
import * as t46 from "@tpl/news-card-desk";
import * as t47 from "@tpl/number-counter";
import * as t48 from "@tpl/number-slab-pop";
import * as t49 from "@tpl/numbered-step-stack";
import * as t50 from "@tpl/orbit-drift";
import * as t51 from "@tpl/outline-box-title";
import * as t52 from "@tpl/overexpose-flip-transition";
import * as t53 from "@tpl/parallel-items-with-host";
import * as t54 from "@tpl/particle-weld-transition";
import * as t55 from "@tpl/pencil-sketch-draw";
import * as t56 from "@tpl/per-character-rise";
import * as t57 from "@tpl/pip-zoom-box";
import * as t58 from "@tpl/pullback-cool-transition";
import * as t59 from "@tpl/push-through-transition";
import * as t60 from "@tpl/quote-bracket-pull";
import * as t61 from "@tpl/quote-card";
import * as t62 from "@tpl/quote-hold-arrow";
import * as t63 from "@tpl/rack-focus-pair";
import * as t64 from "@tpl/scribble-annotation";
import * as t65 from "@tpl/shape-wipe-transition";
import * as t66 from "@tpl/slab-punch-title";
import * as t67 from "@tpl/slow-pull-reveal";
import * as t68 from "@tpl/slow-push-in";
import * as t69 from "@tpl/soft-blur-in";
import * as t70 from "@tpl/speed-slab-title";
import * as t71 from "@tpl/split-60-40-story";
import * as t72 from "@tpl/split-compare-slider";
import * as t73 from "@tpl/stack-fan-out";
import * as t74 from "@tpl/stage-keyframe-tour";
import * as t75 from "@tpl/step-timeline-vertical";
import * as t76 from "@tpl/still-layout-relay";
import * as t77 from "@tpl/strike-and-replace";
import * as t78 from "@tpl/subscribe-cta";
import * as t79 from "@tpl/sway-parallax";
import * as t80 from "@tpl/terminal-typing-log";
import * as t81 from "@tpl/tilt-3d-page";
import * as t82 from "@tpl/tracking-in";
import * as t83 from "@tpl/type-contrast-emphasis";
import * as t84 from "@tpl/typewriter-reveal";
import * as t85 from "@tpl/ui-flow-theater";
import * as t86 from "@tpl/ui-prop-theater";
import * as t87 from "@tpl/whip-pan-transition";
import * as t88 from "@tpl/x-follow-card";

export type TplModule = {
  default?: React.ComponentType<Record<string, unknown>>;
  meta?: { durationInFrames?: number };
};

export const TPL_MODULES: Record<string, TplModule> = {
  "alt-block-lines": t0 as unknown as TplModule,
  "bar-chart-growth": t1 as unknown as TplModule,
  "bed-echo-blur": t2 as unknown as TplModule,
  "behind-text-title": t3 as unknown as TplModule,
  "black-slam-transition": t4 as unknown as TplModule,
  "callout-line-label": t5 as unknown as TplModule,
  "caret-wipe-transition": t6 as unknown as TplModule,
  "chapter-progress-list": t7 as unknown as TplModule,
  "chapter-title-card": t8 as unknown as TplModule,
  "chart-grow": t9 as unknown as TplModule,
  "chat-gpt": t10 as unknown as TplModule,
  "chat-message-flow": t11 as unknown as TplModule,
  "chevron-lower-third": t12 as unknown as TplModule,
  "claude-code": t13 as unknown as TplModule,
  "color-slam-beat-card": t14 as unknown as TplModule,
  "converging-arrows": t15 as unknown as TplModule,
  "corner-bracket-frame": t16 as unknown as TplModule,
  "count-badge-title": t17 as unknown as TplModule,
  "cursor-actor-demo": t18 as unknown as TplModule,
  "cursor-locked-zoom": t19 as unknown as TplModule,
  "danmu-bubble-praise": t20 as unknown as TplModule,
  "douyin-follow-card": t21 as unknown as TplModule,
  "evidence-scroll-tour": t22 as unknown as TplModule,
  "filmstrip-conveyor": t23 as unknown as TplModule,
  "focus-dim-spotlight": t24 as unknown as TplModule,
  "glass-code-walk": t25 as unknown as TplModule,
  "gooey-morph": t26 as unknown as TplModule,
  "grid-to-hero": t27 as unknown as TplModule,
  "hand-drawn-ellipse": t28 as unknown as TplModule,
  "highlighter-sweep": t29 as unknown as TplModule,
  "host-shrink-to-chip": t30 as unknown as TplModule,
  "impact-open-title": t31 as unknown as TplModule,
  "info-term-card": t32 as unknown as TplModule,
  "ink-underline": t33 as unknown as TplModule,
  "keyword-pop-highlight": t34 as unknown as TplModule,
  "line-by-line-slide": t35 as unknown as TplModule,
  "line-chart-story-draw": t36 as unknown as TplModule,
  "logo-enter": t37 as unknown as TplModule,
  "long-take-world": t38 as unknown as TplModule,
  "lower-third-nameplate": t39 as unknown as TplModule,
  "magnifier-detail": t40 as unknown as TplModule,
  "map-route-pin": t41 as unknown as TplModule,
  "media-pop-in": t42 as unknown as TplModule,
  "metric-with-sparkline": t43 as unknown as TplModule,
  "motion-blur-slam-in": t44 as unknown as TplModule,
  "multi-still-tour": t45 as unknown as TplModule,
  "news-card-desk": t46 as unknown as TplModule,
  "number-counter": t47 as unknown as TplModule,
  "number-slab-pop": t48 as unknown as TplModule,
  "numbered-step-stack": t49 as unknown as TplModule,
  "orbit-drift": t50 as unknown as TplModule,
  "outline-box-title": t51 as unknown as TplModule,
  "overexpose-flip-transition": t52 as unknown as TplModule,
  "parallel-items-with-host": t53 as unknown as TplModule,
  "particle-weld-transition": t54 as unknown as TplModule,
  "pencil-sketch-draw": t55 as unknown as TplModule,
  "per-character-rise": t56 as unknown as TplModule,
  "pip-zoom-box": t57 as unknown as TplModule,
  "pullback-cool-transition": t58 as unknown as TplModule,
  "push-through-transition": t59 as unknown as TplModule,
  "quote-bracket-pull": t60 as unknown as TplModule,
  "quote-card": t61 as unknown as TplModule,
  "quote-hold-arrow": t62 as unknown as TplModule,
  "rack-focus-pair": t63 as unknown as TplModule,
  "scribble-annotation": t64 as unknown as TplModule,
  "shape-wipe-transition": t65 as unknown as TplModule,
  "slab-punch-title": t66 as unknown as TplModule,
  "slow-pull-reveal": t67 as unknown as TplModule,
  "slow-push-in": t68 as unknown as TplModule,
  "soft-blur-in": t69 as unknown as TplModule,
  "speed-slab-title": t70 as unknown as TplModule,
  "split-60-40-story": t71 as unknown as TplModule,
  "split-compare-slider": t72 as unknown as TplModule,
  "stack-fan-out": t73 as unknown as TplModule,
  "stage-keyframe-tour": t74 as unknown as TplModule,
  "step-timeline-vertical": t75 as unknown as TplModule,
  "still-layout-relay": t76 as unknown as TplModule,
  "strike-and-replace": t77 as unknown as TplModule,
  "subscribe-cta": t78 as unknown as TplModule,
  "sway-parallax": t79 as unknown as TplModule,
  "terminal-typing-log": t80 as unknown as TplModule,
  "tilt-3d-page": t81 as unknown as TplModule,
  "tracking-in": t82 as unknown as TplModule,
  "type-contrast-emphasis": t83 as unknown as TplModule,
  "typewriter-reveal": t84 as unknown as TplModule,
  "ui-flow-theater": t85 as unknown as TplModule,
  "ui-prop-theater": t86 as unknown as TplModule,
  "whip-pan-transition": t87 as unknown as TplModule,
  "x-follow-card": t88 as unknown as TplModule,
};
